# Generated by Django 4.2 on 2025-02-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressee',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
