# Generated by Django 4.2 on 2025-02-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_addressee_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressee',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='addressee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dni',
        ),
        migrations.AddField(
            model_name='addressee',
            name='municipe',
            field=models.CharField(default='no definido', max_length=20),
        ),
        migrations.AddField(
            model_name='addressee',
            name='province',
            field=models.CharField(default='no definido', max_length=20),
        ),
        migrations.AlterField(
            model_name='addressee',
            name='address',
            field=models.CharField(default='no definido', max_length=150),
        ),
        migrations.AlterField(
            model_name='addressee',
            name='full_name',
            field=models.CharField(default='no definido', max_length=120),
        ),
        migrations.AlterField(
            model_name='addressee',
            name='phone_number',
            field=models.CharField(default='no definido', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='no definido', max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='no definido', max_length=20),
        ),
    ]
