# Generated by Django 4.2 on 2025-02-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_remove_addressee_dni_remove_addressee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressee',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='addressee',
            name='full_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='addressee',
            name='municipe',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addressee',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addressee',
            name='province',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
