# Generated by Django 4.2 on 2025-02-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_package_imagepackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='payment_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
