# Generated by Django 4.2 on 2025-02-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_alter_package_payment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='payment_method',
            field=models.CharField(choices=[('1', 'efectivo'), ('2', 'transferencia'), ('3', 'tarjeta')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='package',
            name='state',
            field=models.CharField(choices=[('1', 'en proceso'), ('2', 'completado')], default='1', max_length=1),
        ),
    ]
