# Generated by Django 4.2 on 2025-02-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_alter_package_payment_method_alter_package_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'en proceso'), ('2', 'completado')], default='1', max_length=1)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('packages', models.ManyToManyField(blank=True, to='package.package')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
