# Generated by Django 4.2 on 2025-02-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('1', 'armando'), ('2', 'en camino'), ('3', 'completado')], default='1', max_length=1),
        ),
    ]
