# Generated by Django 4.2 on 2025-02-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0009_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='orders', to='package.package'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('1', 'gestionando'), ('2', 'completado'), ('3', 'en camino'), ('4', 'entregado')], default='1', max_length=1),
        ),
    ]
