# Generated by Django 4.2 on 2025-02-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_alter_order_packages_alter_order_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressee',
            options={'verbose_name': 'Destinatario', 'verbose_name_plural': 'Destinatarios'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='imagepackage',
            options={'verbose_name': 'Imágen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Envío', 'verbose_name_plural': 'Envíos'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Paquete', 'verbose_name_plural': 'Paquetes'},
        ),
        migrations.AlterField(
            model_name='addressee',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
