# Generated by Django 4.2 on 2025-02-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_alter_addressee_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='bulk',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='state',
            field=models.CharField(choices=[('1', 'en proceso'), ('2', 'completado'), ('3', 'entregado')], default='1', max_length=1),
        ),
    ]
