# Generated by Django 4.2 on 2025-02-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0012_package_bulk_package_delivery_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delivery_code',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
