# Generated by Django 4.2 on 2025-02-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_customer_delivery_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
