# Generated by Django 4.2 on 2025-02-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0014_alter_customer_delivery_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('1', 'completado'), ('2', 'en camino'), ('3', 'entregado')], default='1', max_length=1),
        ),
    ]
