# Generated by Django 4.2 on 2025-02-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0015_alter_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
