# Generated by Django 4.2 on 2025-03-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0017_package_delivery_user_email_package_delivery_user_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('1', 'marítimo'), ('2', 'aéreo'), ('3', 'aéreo express')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('1', 'gestionando'), ('2', 'en camino'), ('3', 'entregado')], default='1', max_length=1),
        ),
    ]
