# Generated by Django 4.2 on 2025-03-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0018_package_type_alter_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('1', 'marítimo'), ('2', 'aéreo'), ('3', 'aéreo express')], default='1', max_length=1),
        ),
    ]
